services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "/var/docker-services/config/homepage:/app/config"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3000,127.0.0.1:3000,172.16.0.116:3000,homepage.internal.lordgasmic.com
